public enum NodeActionTypeEntity {
    case download
    case exportFile
    case copy
    case move
    case info
    case favourite
    case label
    case leaveSharing
    case rename
    case removeLink
    case moveToRubbishBin
    case remove
    case removeSharing
    case `import`
    case viewVersions
    case revertVersion
    case select
    case restore
    case saveToPhotos
    case manageShare
    case shareFolder
    case manageLink
    case shareLink
    case sendToChat
    case pdfPageView
    case pdfThumbnailView
    case forward
    case viewInFolder
    case clear
    case retry
    case search
    case list
    case thumbnail
    case sort
    case editTextFile
    case disputeTakedown
    case verifyContact
    case restoreBackup
    case mediaDiscovery
    case hide
    case unhide
    case removeVideoFromVideoPlaylist
    case moveVideoInVideoPlaylistContentToRubbishBin
    case addTo
    case addToAlbum
}
