public enum BackupSubstateEntity: Sendable {
    case noSyncError
    case unknownError
    case unsupportedFileSystem
    case invalidRemoteType
    case invalidLocalType
    case initialScanFailed
    case localPathTemporaryUnavailable
    case localPathUnavailable
    case remoteNodeNotFound
    case storageOverquota
    case accountExpired
    case foreignTargetOverstorage
    case remotePathHasChanged
    case shareNonFullAccess
    case localFilesystemMismatch
    case putNodesError
    case activeSyncBelowPath
    case activeSyncAbovePath
    case remoteNodeMovedToRubbish
    case remoteNodeInsideRubbish
    case vBoxSharedFolderUnsupported
    case localPathSyncCollision
    case accountBlocked
    case unknownTemporaryError
    case tooManyActionPackets
    case loggedOut
    case wholeAccountRefetched
    case missingParentNode
    case backupModified
    case backupSourceNotBelowDrive
    case syncConfigWriteFailure
    case activeSyncSamePath
    case couldNotMoveCloudNodes
    case couldNotCreateIgnoreFile
    case syncConfigReadFailure
    case unknownDrivePath
    case invalidScanInterval
    case notificationSystemUnavailable
    case unableToAddWatch
    case unableToRetrieveRootFSID
    case unableToOpenDatabase
    case insufficientDiskSpace
    case failureAccessingPersistentStorage
    case mismatchOfRootRSID
    case filesystemFileIdsAreUnstable
}
