typedef NS_ENUM (NSInteger, DisplayMode) {
    DisplayModeUnknown = -1,
    DisplayModeCloudDrive = 0,
    DisplayModeRubbishBin,
    DisplayModeSharedItem,
    DisplayModeNodeInfo,
    DisplayModeNodeVersions,
    DisplayModeFolderLink,
    DisplayModeFileLink,
    DisplayModeNodeInsideFolderLink,
    DisplayModeRecents,
    DisplayModePublicLinkTransfers,
    DisplayModeTransfers,
    DisplayModeTransfersFailed,
    DisplayModeChatAttachment,
    DisplayModeChatSharedFiles,
    DisplayModePreviewDocument,
    DisplayModeTextEditor,
    DisplayModeBackup,
    DisplayModeMediaDiscovery,
    DisplayModePhotosFavouriteAlbum,
    DisplayModePhotosAlbum,
    DisplayModePhotosTimeline,
    DisplayModePreviewPdfPage,
    DisplayModeAlbumLink,
    DisplayModeVideoPlaylistContent
};
