
typedef NS_ENUM (NSInteger, MegaNodeActionType) {
    MegaNodeActionTypeDownload = 0,
    MegaNodeActionTypeShare,
    MegaNodeActionTypeCopy,
    MegaNodeActionTypeMove,
    MegaNodeActionTypeInfo,
    MegaNodeActionTypeLeaveSharing,
    MegaNodeActionTypeRename,
    MegaNodeActionTypeRemoveLink,
    MegaNodeActionTypeMoveToRubbishBin,
    MegaNodeActionTypeRemove,
    MegaNodeActionTypeRemoveSharing,
    MegaNodeActionTypeImport,
    MegaNodeActionTypeRevertVersion,
    MegaNodeActionTypeSelect,
    MegaNodeActionTypeRestore,
    MegaNodeActionTypeSaveToPhotos,
    MegaNodeActionTypeManageShare,
    MegaNodeActionTypeShareFolder,
    MegaNodeActionTypeManageLink,
    MegaNodeActionTypeGetLink,
    MegaNodeActionTypeSendToChat,
    MegaNodeActionTypePdfPageView,
    MegaNodeActionTypePdfThumbnailView,
    MegaNodeActionTypeForward,
    MegaNodeActionTypeSearch,
};
