public enum RemoteFeatureFlag: String, Sendable {
    case chatMonetisation = "chmon"
    case externalAds = "adse"
    case noteToSelfChat = "n2s"
    case appleExternalPurchase = "aep"
    case dotAppDomainExtension = "site"
    case iosVideoPlayerRevamp = "ivpr"
    case iosAppPerformanceMonitoring = "iapm"
    case iosNewYearlyPlanCard = "inypc"
    case iosCameraUploadBreakdown = "icub"
    case iosMediaRevamp = "imrv"
    case iosAlbumMasonryLayout = "iaml"
    case iosNewFolderLink = "infl"
    case iosBackgroundContinuedProcessingTransfer = "ibcpt"
    case iosHomeRevampPhaseOne = "ihr1"
    case iosManualUploadPhotos = "imup"
    case iosPlatformDiskSpaceQuery = "ipdsq"
}
