public enum RemoteFeatureFlag: String, Sendable {
    case chatMonetisation = "chmon"
    case externalAds = "adse"
    case noteToSelfChat = "n2s"
    case appleExternalPurchase = "aep"
    case dotAppDomainExtension = "site"
    case iosVideoPlayerRevamp = "ivpr"
    case iosAppPerformanceMonitoring = "iapm"
    case iosNewYearlyPlanCard = "inypc"
    case iosCameraUploadBreakdown = "icub"
    case iosAlbumMasonryLayout = "iaml"
    case iosBackgroundContinuedProcessingTransfer = "ibcpt"
    case iosManualUploadPhotos = "imup"
    case iosPlatformDiskSpaceQuery = "ipdsq"
    case iosTransferLiveActivity = "itla"
    case iosUploadOnlyNewPhotos = "iuonp"
    case iosSkipSdkTeardownOnTermination = "istd"
    case iosMediaTimelinePagination = "imtp"
    case iosQuotaWarningsRevamp = "iqwr"
    case iosUpgradeAccountPlanRevamp = "iuapr"
}
