import SwiftUI

public struct MEGAImageBundle {
    public static var megaLogoGrayscale: Image { Image(.megaLogoGrayscale) }
    public static var recentsEmptyState: Image { Image(.recentsEmptyState) }
    public static var favouritesEmptyState: Image { Image(.favouritesEmptyState) }
    public static var offlineEmptyState: Image { Image(.offlineEmptyState) }
    public static var versioned: Image { Image(.versioned) }
    public static var recentUpload: Image { Image(.recentUpload) }
    public static var standardDisclosureIndicatorDesignToken: Image { Image(.standardDisclosureIndicatorDesignToken) }
    public static var restore: Image { Image(.restore) }
    public static var link: Image { Image(.link) }
    public static var offline: Image { Image(.offline) }
    public static var rubbishBin: Image { Image(.rubbishBin) }
    public static var noResultsDocuments: Image { Image(.noResultsDocuments) }
    public static var noResultsAudio: Image { Image(.noResultsAudio) }
    public static var noResultsVideo: Image { Image(.noResultsVideo) }
    public static var noResultsImages: Image { Image(.noResultsImages) }
    public static var noResultsFolders: Image { Image(.noResultsFolders) }
    public static var noResultsPresentations: Image { Image(.noResultsPresentations) }
    public static var noResultsArchives: Image { Image(.noResultsArchives) }
    public static var searchEmptyState: Image { Image(.searchEmptyState) }
    public static var turquoiseCheckmark: Image { Image(.turquoiseCheckmark) }
    public static var closeBanner: Image { Image(.closeBanner) }
    public static var upgradeToProPlan: Image { Image(.upgradeToProPlan) }
    public static var allPhotosEmptyState: Image { Image(.allPhotosEmptyState) }
    public static var videoEmptyState: Image { Image(.videoEmptyState) }
    public static var cameraEmptyState: Image { Image(.cameraEmptyState) }
    public static var info: Image { Image(.info) }
    public static var notificationCta: Image { Image(.notificationCta) }
    public static var cameraBackupsCta: Image { Image(.cameraBackupsCta) }
    public static var callControlCameraDisabled: Image { Image(.callControlCameraDisabled) }
    public static var callControlCameraEnabled: Image { Image(.callControlCameraEnabled) }
    public static var callControlMicDisabled: Image { Image(.callControlMicDisabled) }
    public static var callControlMicEnabled: Image { Image(.callControlMicEnabled) }
    public static var callControlSpeakerEnabled: Image { Image(.callControlSpeakerEnabled) }
    public static var callControlSpeakerDisabled: Image { Image(.callControlSpeakerDisabled) }
    public static var saveToPhotos: Image { Image(.saveToPhotos) }
    public static var capture: Image { Image(.capture) }
    public static var subscriptionFeatureCloud: Image { Image(.subscriptionFeatureCloud) }
    public static var subscriptionFeatureTransfers: Image { Image(.subscriptionFeatureTransfers) }
    public static var subscriptionFeatureVPN: Image { Image(.subscriptionFeatureVPN) }
    public static var subscriptionFeatureTransfersPWM: Image { Image(.subscriptionFeatureTransfersPWM) }
    public static var subscriptionImageHeader: Image { Image(.subscriptionImageHeader) }
    public static var subscriptionImageHeaderLandscape: Image { Image(.subscriptionImageHeaderLandscape) }
    public static var eyeOff: Image { Image(.eyeOff) }
    public static var eyeOffRegular: Image { Image(.eyeOffRegular) }
    public static var imagesRegular: Image { Image(.imagesRegular) }
    public static var eyeRegular: Image { Image(.eyeRegular) }
    public static var onboardingLock: Image { Image(.onboardingLock) }
    public static var occurrences: Image { Image(.occurrences) }
    public static var makeCallRoundToken: Image { Image(.makeCallRoundToken) }
    public static var edittext: Image { Image(.edittext) }
    public static var mutedChat: Image { Image(.mutedChat) }
    public static var speakerOnBluetooth: Image { Image(.speakerOnBluetooth) }
    public static var waitingRoomDeny: Image { Image(.waitingRoomDeny) }
    public static var waitingRoomAdmit: Image { Image(.waitingRoomAdmit) }
    public static var closeBannerButton: Image { Image(.closeBannerButton) }
    public static var closeCircle: Image { Image(.closeCircle) }
    public static var shareLink: Image { Image(.shareLink) }
    public static var joinMeeting2: Image { Image(.joinMeeting2) }
    public static var startMeeting2: Image { Image(.startMeeting2) }
    public static var editMeeting: Image { Image(.editMeeting) }
    public static var archiveChatMenu: Image { Image(.archiveChatMenu) }
    public static var noInternetEmptyState: Image { Image(.noInternetEmptyState) }
    public static var inviteToChatDesignToken: Image { Image(.inviteToChatDesignToken) }
    public static var check: Image { Image(.check) }
    public static var enableChatNotifications: Image { Image(.enableChatNotifications) }
    public static var cuStatusUploadSync: Image { Image(.cuStatusUploadSync) }
    public static var cuStatusUploadInProgressCheckMark: Image { Image(.cuStatusUploadInProgressCheckMark) }
    public static var cuStatusUploadCompleteGreenCheckMark: Image { Image(.cuStatusUploadCompleteGreenCheckMark) }
    public static var cuStatusUploadIdleCheckMark: Image { Image(.cuStatusUploadIdleCheckMark) }
    public static var cuStatusUploadWarningCheckMark: Image { Image(.cuStatusUploadWarningCheckMark) }
    public static var cuStatusEnable: Image { Image(.cuStatusEnable) }
    public static var cuStatusUpload: Image { Image(.cuStatusUpload) }
    public static var selectAllItems: Image { Image(.selectAllItems) }
    public static var enableCameraUploadsPhotoLibraryEmpty: Image { Image(.enableCameraUploadsPhotoLibraryEmpty) }
    public static var cloudEmptyState: Image { Image(.cloudEmptyState) }
    public static var rubbishEmptyState: Image { Image(.rubbishEmptyState) }
    public static var folderEmptyState: Image { Image(.folderEmptyState) }
    public static var `import`: Image { Image(.import) }
    public static var textfile: Image { Image(.textfile) }
    public static var newFolder: Image { Image(.newFolder) }
    public static var scanDocument: Image { Image(.scanDocument) }
    public static var chatEmptyStateNew: Image { Image(.chatEmptyStateNew) }
    public static var meetingsEmptyStateNew: Image { Image(.meetingsEmptyStateNew) }
    public static var newChatEmptyContacts: Image { Image(.newChatEmptyContacts) }
    public static var readOnlyChat: Image { Image(.readOnlyChat) }
    public static var moderator: Image { Image(.moderator) }
    public static var standard: Image { Image(.standard) }
    public static var startMeeting: Image { Image(.startMeeting) }
    public static var joinAMeeting: Image { Image(.joinAMeeting) }
    public static var scheduleMeeting: Image { Image(.scheduleMeeting) }
    public static var privateChat: Image { Image(.privateChat) }
    public static var markUnreadMenu: Image { Image(.markUnreadMenu) }
    public static var allowNonHostToAddParticipant: Image { Image(.allowNonHostToAddParticipant) }
    public static var enableWaitingRoom: Image { Image(.enableWaitingRoom) }
    public static var callControlSwitchCameraEnabled: Image { Image(.callControlSwitchCameraEnabled) }
    public static var callControlSwitchCameraDisabled: Image { Image(.callControlSwitchCameraDisabled) }
    public static var callControlEndCall: Image { Image(.callControlEndCall) }
    public static var callContextMenu: Image { Image(.callContextMenu) }
    public static var videoList: Image { Image(.videoList) }
    public static var videoPlaylistThumbnailFallback: Image { Image(.videoPlaylistThumbnailFallback) }
    public static var linked: Image { Image(.linked) }
    public static var linksSegmentControler: Image { Image(.linksSegmentControler) }
    public static var folderIncoming: Image { Image(.folderIncoming) }
    public static var folderOutgoing: Image { Image(.folderOutgoing) }
    public static var folderChat: Image { Image(.folderChat) }
    public static var placeholder: Image { Image(.placeholder) }
    public static var rectangleVideoStack: Image { Image(.rectangleVideoStack) }
    public static var rectangleVideoStackOutline: Image { Image(.rectangleVideoStackOutline) }
    public static var moreList: Image { Image(.moreList) }
    public static var playlist: Image { Image(.playlist) }
    public static var navigationBarAdd: Image { Image(.navigationbarAdd) }
    public static var timeline: Image { Image(.timeline) }
    public static var clockMediumThin: Image { Image(.clockMediumThin) }
    public static var glassPlaylist: Image { Image(.glassPlaylist) }
    public static var splashScreenMEGALogo: Image { Image(.splashScreenMEGALogo) }
    public static var glassSearch: Image { Image(.glassSearch) }
    public static var noteToSelf: Image { Image(.noteToSelf) }
    public static var noteToSelfSmall: Image { Image(.noteToSelfSmall) }
    public static var noteToSelfBlue: Image { Image(.noteToSelfBlue) }
    public static var sharedFiles: Image { Image(.sharedFiles) }
    public static var clearChatHistory: Image { Image(.clearChatHistory) }
    public static var unArchiveChat: Image { Image(.unArchiveChat) }
    public static var archiveChat: Image { Image(.archiveChat) }
    public static var sharedFilesInfo: Image { Image(.sharedFilesInfo) }
    public static var manageChatHistory: Image { Image(.manageChatHistory) }
    public static var meetingLink: Image { Image(.meetingLink) }
    public static var onboardingCarousel1: Image { Image(.onboardingCarousel1) }
    public static var onboardingCarousel2: Image { Image(.onboardingCarousel2) }
    public static var onboardingCarousel3: Image { Image(.onboardingCarousel3) }
    public static var onboardingCarousel4: Image { Image(.onboardingCarousel4) }
    public static var photoCardPlaceholder: Image { Image(.photoCardPlaceholder) }
    public static var enableCameraUploadsBannerIcon: Image { Image(.enableCameraUploadsBannerIcon) }
    public static var cuBannerChevronRevamp: Image { Image(.cuBannerChevronRevamp) }
    public static var favouritePlaylistThumbnail: Image { Image(.favouritePlaylistThumbnail) }
    public static var addContactMeetings: Image { Image(.addContactMeetings) }
    public static var filetypeFolder: Image { Image(.filetypeFolder) }
    public static var filetype3D: Image { Image(.filetype3D) }
    public static var filetypeRaw: Image { Image(.filetypeRaw) }
    public static var filetypeVideo: Image { Image(.filetypeVideo) }
    public static var filetypeAudio: Image { Image(.filetypeAudio) }
    public static var filetypeCompressed: Image { Image(.filetypeCompressed) }
    public static var filetypePhotoshop: Image { Image(.filetypePhotoshop) }
    public static var filetypeWebLang: Image { Image(.filetypeWebLang) }
    public static var filetypeAfterEffects: Image { Image(.filetypeAfterEffects) }
    public static var filetypeIllustrator: Image { Image(.filetypeIllustrator) }
    public static var filetypeText: Image { Image(.filetypeText) }
    public static var filetypeExecutable: Image { Image(.filetypeExecutable) }
    public static var filetypeVector: Image { Image(.filetypeVector) }
    public static var filetypeImages: Image { Image(.filetypeImages) }
    public static var filetypeWebData: Image { Image(.filetypeWebData) }
    public static var filetypeWord: Image { Image(.filetypeWord) }
    public static var filetypeCAD: Image { Image(.filetypeCAD) }
    public static var filetypeDmg: Image { Image(.filetypeDmg) }
    public static var filetypeFont: Image { Image(.filetypeFont) }
    public static var filetypeSpreadsheet: Image { Image(.filetypeSpreadsheet) }
    public static var filetypeIndesign: Image { Image(.filetypeIndesign) }
    public static var filetypePowerpoint: Image { Image(.filetypePowerpoint) }
    public static var filetypeKeynote: Image { Image(.filetypeKeynote) }
    public static var filetypeNumbers: Image { Image(.filetypeNumbers) }
    public static var filetypeGeneric: Image { Image(.filetypeGeneric) }
    public static var filetypeOpenoffice: Image { Image(.filetypeOpenoffice) }
    public static var filetypeExcel: Image { Image(.filetypeExcel) }
    public static var filetypePages: Image { Image(.filetypePages) }
    public static var filetypePdf: Image { Image(.filetypePdf) }
    public static var filetypePremiere: Image { Image(.filetypePremiere) }
    public static var filetypeSketch: Image { Image(.filetypeSketch) }
    public static var filetypeTorrent: Image { Image(.filetypeTorrent) }
    public static var filetypeUrl: Image { Image(.filetypeUrl) }
    public static var filetypeExperiencedesign: Image { Image(.filetypeExperiencedesign) }
    public static var filetypeFolderCamera: Image { Image(.filetypeFolderCamera) }
    // MARK: - Device Center
    public static var android: Image { Image(.android) }
    public static var drive: Image { Image(.drive) }
    public static var ios: Image { Image(.ios) }
    public static var mobile: Image { Image(.mobile) }
    public static var pc: Image { Image(.pc) }
    public static var pcLinux: Image { Image(.pcLinux) }
    public static var pcMac: Image { Image(.pcMac) }
    public static var pcWindows: Image { Image(.pcWindows) }
    public static var backupFolder: Image { Image(.backupFolder) }
    public static var cameraUploadsFolder: Image { Image(.cameraUploadsFolder) }
    public static var syncFolder: Image { Image(.syncFolder) }
    public static var attentionNeeded: Image { Image(.attentionNeeded) }
    public static var disabled: Image { Image(.disabled) }
    public static var error: Image { Image(.error) }
    public static var inactive: Image { Image(.inactive) }
    public static var noCameraUploads: Image { Image(.noCameraUploads) }
    public static var outOfQuota: Image { Image(.outOfQuota) }
    public static var paused: Image { Image(.paused) }
    public static var updating: Image { Image(.updating) }
    public static var upToDate: Image { Image(.upToDate) }
    public static var externalLink: Image { Image(.externalLink) }
}
