import UIKit

public struct MEGAUIColorBundle {
    public static var whiteFFFFFF: UIColor { UIColor.whiteFFFFFF }
    public static var black000000: UIColor { UIColor.black000000 }
    public static var black2C2C2E: UIColor { UIColor.black2C2C2E }
    public static var proAccountRedProIII: UIColor { UIColor.proAccountRedProIII }
    public static var black1C1C1E: UIColor { UIColor.black1C1C1E }
    public static var proAccountLITE: UIColor { UIColor.proAccountLITE }
    public static var proAccountRedProI: UIColor { UIColor.proAccountRedProI }
    public static var proAccountRedProII: UIColor { UIColor.proAccountRedProII }
    public static var grayDBDBDB: UIColor { UIColor.grayDBDBDB }
    public static var grayE2E2E2: UIColor { UIColor.grayE2E2E2 }
    public static var grayBBBBBB: UIColor { UIColor.grayBBBBBB }
    public static var gray999999: UIColor { UIColor.gray999999 }
    public static var green00C29A4D: UIColor { UIColor.green00C29A4D }
    public static var black363638: UIColor { UIColor.black363638 }
    public static var verifyEmailFirstGradient: UIColor { UIColor.verifyEmailFirstGradient }
    public static var verifyEmailSecondGradient: UIColor { UIColor.verifyEmailSecondGradient }
    public static var gray04040F: UIColor { UIColor.gray04040F }
    public static var whiteFFFFFF30: UIColor { UIColor.whiteFFFFFF30 }
    public static var pasteImageBorder: UIColor { UIColor.pasteImageBorder }
    public static var explorerForegroundDark: UIColor { UIColor.explorerForegroundDark }
    public static var gradientRed: UIColor { UIColor.gradientRed }
    public static var gradientPink: UIColor { UIColor.gradientPink }
    public static var explorerDocumentsFirstGradient: UIColor { UIColor.explorerDocumentsFirstGradient }
    public static var explorerDocumentsSecondGradient: UIColor { UIColor.explorerDocumentsSecondGradient }
    public static var explorerAudioFirstGradient: UIColor { UIColor.explorerAudioFirstGradient }
    public static var explorerAudioSecondGradient: UIColor { UIColor.explorerAudioSecondGradient }
    public static var explorerGradientLightBlue: UIColor { UIColor.explorerGradientLightBlue }
    public static var explorerGradientDarkBlue: UIColor { UIColor.explorerGradientDarkBlue }
    public static var whiteF7F7F7: UIColor { UIColor.whiteF7F7F7 }
    public static var pageBgColorDark: UIColor { UIColor.pageBgColorDark }
    public static var upgradeAccountPrimaryText: UIColor { UIColor.upgradeAccountPrimaryText }
    public static var gray8E8E93: UIColor { UIColor.gray8E8E93 }
    public static var green00A88680: UIColor { UIColor.green00A88680 }
    public static var black00000015: UIColor { UIColor.black00000015 }
    public static var yellowFED429: UIColor { UIColor.yellowFED429 }
    public static var whiteF2F2F2: UIColor { UIColor.whiteF2F2F2 }
    public static var chatAvatarBackground: UIColor { UIColor.chatAvatarBackground }
    public static var whiteFFFFFF00: UIColor { UIColor.whiteFFFFFF00 }
    public static var redFF3B30: UIColor { UIColor.redFF3B30 }
    public static var orangeF9B35F: UIColor { UIColor.orangeF9B35F }
    public static var orangeE68F4D: UIColor { UIColor.orangeE68F4D }
    public static var blue02A2FF: UIColor { UIColor.blue02A2FF }
    public static var blue0274CC: UIColor { UIColor.blue0274CC }
    public static var blue00ACBF: UIColor { UIColor.blue00ACBF }
    public static var blue0095A6: UIColor { UIColor.blue0095A6 }
    public static var redF288C2: UIColor { UIColor.redF288C2 }
    public static var redCA75D1: UIColor { UIColor.redCA75D1 }
    public static var whiteEFEFEF: UIColor { UIColor.whiteEFEFEF }
    public static var callAvatarBackground: UIColor { UIColor.callAvatarBackground }
    public static var callAvatarBackgroundGradient: UIColor { UIColor.callAvatarBackgroundGradient }
    public static var chatStatusOnline: UIColor { UIColor.chatStatusOnline }
    public static var chatStatusOffline: UIColor { UIColor.chatStatusOffline }
    public static var chatStatusAway: UIColor { UIColor.chatStatusAway }
    public static var chatStatusBusy: UIColor { UIColor.chatStatusBusy }
    public static var whiteFFD60008: UIColor { UIColor.whiteFFD60008 }
    public static var black29292C: UIColor { UIColor.black29292C }
    public static var mediaConsumptionDecryptTitleEnabled: UIColor { UIColor.mediaConsumptionDecryptTitleEnabled }
    public static var mediaConsumptionDecryptTitleDisabled: UIColor { UIColor.mediaConsumptionDecryptTitleDisabled }
    public static var green00C29A: UIColor { UIColor.green00C29A }
    public static var grayE4EBEA: UIColor { UIColor.grayE4EBEA }
}
