import UIKit

public struct MEGAUIImageBundle {
    public static var chatNotifications: UIImage { UIImage.chatNotifications }
    public static var iconContacts: UIImage { UIImage.iconContacts }
    public static var groupChatToken: UIImage { UIImage.groupChatToken }
    public static var newMeetingToken: UIImage { UIImage.newMeetingToken }
    public static var joinMeetingToken: UIImage { UIImage.joinMeetingToken }
    public static var inviteContactShare: UIImage { UIImage.inviteContactShare }
    public static var checkBoxSelectedSemantic: UIImage { UIImage.checkBoxSelectedSemantic }
    public static var checkBoxUnselected: UIImage { UIImage.checkBoxUnselected }
    public static var noteToSelfSmall: UIImage { UIImage.noteToSelfSmall }
    public static var noteToSelfBlue: UIImage { UIImage.noteToSelfBlue }
    public static var deviceStorageAlmostFull: UIImage { UIImage.deviceStorageAlmostFull }
    public static var hudDownload: UIImage { UIImage.hudDownload }
    public static var upload: UIImage { UIImage.upload }
    public static var sendToChat: UIImage { UIImage.sendToChat }
    public static var folderChat: UIImage { UIImage.folderChat }
    public static var folderIncoming: UIImage { UIImage.folderIncoming }
    public static var folderOutgoing: UIImage { UIImage.folderOutgoing }
    public static var export: UIImage { UIImage.export }
    public static var shareFolder: UIImage { UIImage.shareFolder }
    public static var verifyContact: UIImage { UIImage.verifyContact }
    public static var offline: UIImage { UIImage.offline }
    public static var info: UIImage { UIImage.info }
    public static var rename: UIImage { UIImage.rename }
    public static var copy: UIImage { UIImage.copy }
    public static var move: UIImage { UIImage.move }
    public static var rubbishBin: UIImage { UIImage.rubbishBin }
    public static var hudMinus: UIImage { UIImage.hudMinus }
    public static var leaveShare: UIImage { UIImage.leaveShare }
    public static var link: UIImage { UIImage.link }
    public static var removeLink: UIImage { UIImage.removeLink }
    public static var removeShare: UIImage { UIImage.removeShare }
    public static var search: UIImage { UIImage.search }
    public static var cancelTransfers: UIImage { UIImage.cancelTransfers }
    public static var `import`: UIImage { UIImage.import }
    public static var versions: UIImage { UIImage.versions }
    public static var history: UIImage { UIImage.history }
    public static var delete: UIImage { UIImage.delete }
    public static var selectItem: UIImage { UIImage.selectItem }
    public static var restore: UIImage { UIImage.restore }
    public static var saveToPhotos: UIImage { UIImage.saveToPhotos }
    public static var pageView: UIImage { UIImage.pageView }
    public static var thumbnailsThin: UIImage { UIImage.thumbnailsThin }
    public static var edittext: UIImage { UIImage.edittext }
    public static var forwardToolbar: UIImage { UIImage.forwardToolbar }
    public static var removeFavourite: UIImage { UIImage.removeFavourite }
    public static var favourite: UIImage { UIImage.favourite }
    public static var label: UIImage { UIImage.label }
    public static var gridThin: UIImage { UIImage.gridThin }
    public static var sort: UIImage { UIImage.sort }
    public static var disputeTakedown: UIImage { UIImage.disputeTakedown }
    public static var mediaDiscovery: UIImage { UIImage.mediaDiscovery }
    public static var helpCircleThinMedium: UIImage { UIImage.helpCircleThinMedium }
    public static var eyeOff: UIImage { UIImage.eyeOff }
    public static var eyeOn: UIImage { UIImage.eyeOn }
    public static var addTo: UIImage { UIImage.addTo }
    public static var standardDisclosureIndicator: UIImage { UIImage.standardDisclosureIndicator }
    public static var hudSuccess: UIImage { UIImage.hudSuccess }
    public static var hudError: UIImage { UIImage.hudError }
    public static var backArrow: UIImage { UIImage.backArrow }
    public static var moreNavigationBar: UIImage { UIImage.moreNavigationBar }
    public static var openSettings: UIImage { UIImage.openSettings }
    public static var tapNotifications: UIImage { UIImage.tapNotifications }
    public static var tapMega: UIImage { UIImage.tapMega }
    public static var allowNotifications: UIImage { UIImage.allowNotifications }
    public static var groupChat: UIImage { UIImage.groupChat }
    public static var turquoiseCheckmark: UIImage { UIImage.turquoiseCheckmark }
    public static var miniplayerClose: UIImage { UIImage.miniplayerClose }
    public static var moreList: UIImage { UIImage.moreList }
    public static var videoList: UIImage { UIImage.videoList }
    public static var downloaded: UIImage { UIImage.downloaded }
    public static var moreGrid: UIImage { UIImage.moreGrid }
    public static var shuffleAudio: UIImage { UIImage.shuffleAudio }
    public static var newest: UIImage { UIImage.newest }
    public static var oldest: UIImage { UIImage.oldest }
    public static var cameraUploadsSettings: UIImage { UIImage.cameraUploadsSettings }
    public static var chatSettings: UIImage { UIImage.chatSettings }
    public static var callsSettings: UIImage { UIImage.callsSettings }
    public static var securitySettings: UIImage { UIImage.securitySettings }
    public static var userInterfaceSettings: UIImage { UIImage.userInterfaceSettings }
    public static var fileManagementSettings: UIImage { UIImage.fileManagementSettings }
    public static var advancedSettings: UIImage { UIImage.advancedSettings }
    public static var helpSettings: UIImage { UIImage.helpSettings }
    public static var aboutSettings: UIImage { UIImage.aboutSettings }
    public static var termsAndPoliciesSettings: UIImage { UIImage.termsAndPoliciesSettings }
    public static var cookieSettings: UIImage { UIImage.cookieSettings }
    public static var iconSettings: UIImage { UIImage.iconSettings }
    public static var isTakedown: UIImage { UIImage.isTakedown }
    public static var warningPermission: UIImage { UIImage.warningPermission }
    public static var searchEmptyState: UIImage { UIImage.searchEmptyState }
    public static var incomingEmptyState: UIImage { UIImage.incomingEmptyState }
    public static var outgoingEmptyState: UIImage { UIImage.outgoingEmptyState }
    public static var linksEmptyState: UIImage { UIImage.linksEmptyState }
    public static var noInternetEmptyState: UIImage { UIImage.noInternetEmptyState }
    public static var lockedAccounts: UIImage { UIImage.lockedAccounts }
    public static var noResultsVideoV2: UIImage { UIImage.noResultsVideoV2 }
    public static var filterChipDownArrow: UIImage { UIImage.filterChipDownArrow }
    public static var favouriteThumbnail: UIImage { UIImage.favouriteThumbnail }
    public static var blackPlayButton: UIImage { UIImage.blackPlayButton }
    public static var linked: UIImage { UIImage.linked }
    public static var navigationbarAdd: UIImage { UIImage.navigationbarAdd }
    public static var rectangleVideoStack: UIImage { UIImage.rectangleVideoStack }
    public static var favouritePlaylistThumbnail: UIImage { UIImage.favouritePlaylistThumbnail }
    public static var grabberIcon: UIImage { UIImage.grabberIcon }
    public static var redSmall: UIImage { UIImage.redSmall }
    public static var orangeSmall: UIImage { UIImage.orangeSmall }
    public static var yellowSmall: UIImage { UIImage.yellowSmall }
    public static var greenSmall: UIImage { UIImage.greenSmall }
    public static var blueSmall: UIImage { UIImage.blueSmall }
    public static var purpleSmall: UIImage { UIImage.purpleSmall }
    public static var greySmall: UIImage { UIImage.greySmall }
    public static var recentlyWatchedVideosEmptyState: UIImage { UIImage.recentlyWatchedVideosEmptyState }
    public static var selectAllItems: UIImage { UIImage.selectAllItems }
    public static var clockPlay: UIImage { UIImage.clockPlay }
    public static var ascending: UIImage { UIImage.ascending }
    public static var descending: UIImage { UIImage.descending }
    public static var largest: UIImage { UIImage.largest }
    public static var smallest: UIImage { UIImage.smallest }
    public static var sortLabel: UIImage { UIImage.sortLabel }
    public static var sortFavourite: UIImage { UIImage.sortFavourite }
    public static var standardDisclosureIndicatorDesignToken: UIImage { UIImage.standardDisclosureIndicatorDesignToken }
    public static var verificationCountry: UIImage { UIImage.verificationCountry }
    public static var phoneNumber: UIImage { UIImage.phoneNumber }
    public static var spotlightFile: UIImage { UIImage.spotlightFile }
    public static var defaultArtwork: UIImage { UIImage.defaultArtwork }
    public static var filterActive: UIImage { UIImage.filterActive }
    public static var moreActionActiveNavigationBar: UIImage { UIImage.moreActionActiveNavigationBar }
    public static var allPhotosEmptyState: UIImage { UIImage.allPhotosEmptyState }
    public static var cameraEmptyState: UIImage { UIImage.cameraEmptyState }
    public static var videoEmptyState: UIImage { UIImage.videoEmptyState }
    public static var spotlightFolder: UIImage { UIImage.spotlightFolder }
    public static var addReactionSmall: UIImage { UIImage.addReactionSmall }
    public static var versioned: UIImage { UIImage.versioned }
    public static var recentUpload: UIImage { UIImage.recentUpload }
    public static var transfersDownload: UIImage { UIImage.transfersDownload }
    public static var completedBadgeDesignToken: UIImage { UIImage.completedBadgeDesignToken }
    public static var errorBadgeDesignToken: UIImage { UIImage.errorBadgeDesignToken }
    public static var overquotaDesignToken: UIImage { UIImage.overquotaDesignToken }
    public static var pauseDesignToken: UIImage { UIImage.pauseDesignToken }
    public static var transfersDownloadDesignToken: UIImage { UIImage.transfersDownloadDesignToken }
    public static var transfersUploadDesignToken: UIImage { UIImage.transfersUploadDesignToken }
    public static var fullAccessPermissions: UIImage { UIImage.fullAccessPermissions }
    public static var readWritePermissions: UIImage { UIImage.readWritePermissions }
    public static var readPermissions: UIImage { UIImage.readPermissions }
    public static var contactRequestDeny: UIImage { UIImage.contactRequestDeny }
    public static var contactRequestAccept: UIImage { UIImage.contactRequestAccept }
    public static var disclosure: UIImage { UIImage.disclosure }
    public static var voiceTip: UIImage { UIImage.voiceTip }
    public static var folderEmptyState: UIImage { UIImage.folderEmptyState }
    public static var cloudDriveIcon: UIImage { UIImage.cloudDriveIcon }
    public static var cameraUploadsIcon: UIImage { UIImage.cameraUploadsIcon }
    public static var miniplayerPause: UIImage { UIImage.miniplayerPause }
    public static var miniplayerPlay: UIImage { UIImage.miniplayerPlay }
    public static var sendButton: UIImage { UIImage.sendButton }
    public static var expand: UIImage { UIImage.expand }
    public static var checkBoxSelected: UIImage { UIImage.checkBoxSelected }
    public static var home: UIImage { UIImage.home }
    public static var chatIcon: UIImage { UIImage.chatIcon }
    public static var sharedItemsIcon: UIImage { UIImage.sharedItemsIcon }
    public static var collapse: UIImage { UIImage.collapse }
    public static var textfile: UIImage { UIImage.textfile }
    public static var capture: UIImage { UIImage.capture }
    public static var scanDocument: UIImage { UIImage.scanDocument }
    public static var explorerCardFavourites: UIImage { UIImage.explorerCardFavourites }
    public static var explorerCardDocs: UIImage { UIImage.explorerCardDocs }
    public static var explorerCardAudio: UIImage { UIImage.explorerCardAudio }
    public static var explorerCardVideoPlayBlue: UIImage { UIImage.explorerCardVideoPlayBlue }
    public static var explorerCardVideoFilmStripsBlue: UIImage { UIImage.explorerCardVideoFilmStripsBlue }
    public static var infoMeetings: UIImage { UIImage.infoMeetings }
    public static var storage: UIImage { UIImage.storage }
    public static var fileSharing: UIImage { UIImage.fileSharing }
    public static var backup: UIImage { UIImage.backup }
    public static var mega: UIImage { UIImage.mega }
    public static var onboardingHeader: UIImage { UIImage.onboardingHeader }
    public static var blockingDiskFull: UIImage { UIImage.blockingDiskFull }
    public static var placeholder: UIImage { UIImage.placeholder }
    public static var linkGetLink: UIImage { UIImage.linkGetLink }
    public static var iconKeyOnly: UIImage { UIImage.iconKeyOnly }
    public static var addFromContacts: UIImage { UIImage.addFromContacts }
    public static var enterUserEmail: UIImage { UIImage.enterUserEmail }
    public static var scanUserQRCode: UIImage { UIImage.scanUserQRCode }
    public static var inviteContactMore: UIImage { UIImage.inviteContactMore }
    public static var megaShareContactLink: UIImage { UIImage.megaShareContactLink }
    public static var cameraIconWhite: UIImage { UIImage.cameraIconWhite }
    public static var cameraIcon: UIImage { UIImage.cameraIcon }
    public static var sendChatDisabled: UIImage { UIImage.sendChatDisabled }
    public static var userMutedBanner: UIImage { UIImage.userMutedBanner }
    public static var callSlotsBanner: UIImage { UIImage.callSlotsBanner }
    public static var accountExpiredAdmin: UIImage { UIImage.accountExpiredAdmin }
    public static var accountExpiredUser: UIImage { UIImage.accountExpiredUser }
    public static var red: UIImage { UIImage.red }
    public static var orange: UIImage { UIImage.orange }
    public static var yellow: UIImage { UIImage.yellow }
    public static var green: UIImage { UIImage.green }
    public static var blue: UIImage { UIImage.blue }
    public static var purple: UIImage { UIImage.purple }
    public static var grey: UIImage { UIImage.grey }
    public static var contactRequests: UIImage { UIImage.contactRequests }
    public static var chatEmptyState: UIImage { UIImage.chatEmptyState }
    public static var moderator: UIImage { UIImage.moderator }
    public static var standard: UIImage { UIImage.standard }
    public static var readOnlyChat: UIImage { UIImage.readOnlyChat }
    public static var sendMessageRoundToken: UIImage { UIImage.sendMessageRoundToken }
    public static var groupAvatar: UIImage { UIImage.groupAvatar }
    public static var newFolder: UIImage { UIImage.newFolder }
    public static var filter: UIImage { UIImage.filter }
    public static var startMeeting: UIImage { UIImage.startMeeting }
    public static var joinAMeeting: UIImage { UIImage.joinAMeeting }
    public static var scheduleMeeting: UIImage { UIImage.scheduleMeeting }
    public static var deleteVideoPlaylist: UIImage { UIImage.deleteVideoPlaylist }
    public static var favicon: UIImage { UIImage.favicon }
    public static var privacyWarningIco: UIImage { UIImage.privacyWarningIco }
    public static var clearChatHistory: UIImage { UIImage.clearChatHistory }
    public static var searchBarIconSemantic: UIImage { UIImage.searchBarIconSemantic }
    public static var downloadGif: UIImage { UIImage.downloadGif }
    public static var playButton: UIImage { UIImage.playButton }
    public static var addContact: UIImage { UIImage.addContact }
    public static var giphyCellBackground: UIImage { UIImage.giphyCellBackground }
    public static var noGIF: UIImage { UIImage.noGIF }
    public static var poweredByGIPHY: UIImage { UIImage.poweredByGIPHY }
    public static var leaveGroup: UIImage { UIImage.leaveGroup }
    public static var groupChatAddParticipant: UIImage { UIImage.groupChatAddParticipant }
    public static var contactGroups: UIImage { UIImage.contactGroups }
    public static var selectAlbumCover: UIImage { UIImage.selectAlbumCover }
    public static var deleteAlbum: UIImage { UIImage.deleteAlbum }
    public static var versionedThumbnail: UIImage { UIImage.versionedThumbnail }
    public static var linkedThumbnail: UIImage { UIImage.linkedThumbnail }
    public static var proLabel: UIImage { UIImage.proLabel }
    public static var hudForbidden: UIImage { UIImage.hudForbidden }
    public static var plan: UIImage { UIImage.plan }
    public static var iconStorage: UIImage { UIImage.iconStorage }
    public static var myAccount: UIImage { UIImage.myAccount }
    public static var iconNotifications: UIImage { UIImage.iconNotifications }
    public static var iconTransfers: UIImage { UIImage.iconTransfers }
    public static var iconAchievements: UIImage { UIImage.iconAchievements }
    public static var deviceCenter: UIImage { UIImage.deviceCenter }
    public static var iconOffline: UIImage { UIImage.iconOffline }
    public static var businessPaymentOverdue: UIImage { UIImage.businessPaymentOverdue }
    public static var favouritesEmptyState: UIImage { UIImage.favouritesEmptyState }
    public static var documentsEmptyState: UIImage { UIImage.documentsEmptyState }
    public static var audioEmptyState: UIImage { UIImage.audioEmptyState }
    public static var waveform0000: UIImage { UIImage.waveform0000 }
    public static var playVoiceClip: UIImage { UIImage.playVoiceClip }
    public static var pauseVoiceClip: UIImage { UIImage.pauseVoiceClip }
    public static var playVoiceClipButton: UIImage { UIImage.playVoiceClipButton }
    public static var closeCircle: UIImage { UIImage.closeCircle }
    public static var inviteToChatDesignToken: UIImage { UIImage.inviteToChatDesignToken }
    public static var archiveChat: UIImage { UIImage.archiveChat }
    public static var markUnreadMenu: UIImage { UIImage.markUnreadMenu }
    public static var mutedChatMenu: UIImage { UIImage.mutedChatMenu }
    public static var callControlSpeakerDisabled: UIImage { UIImage.callControlSpeakerDisabled }
    public static var audioSourceMeetingAction: UIImage { UIImage.audioSourceMeetingAction }
    public static var callControlSpeakerEnabled: UIImage { UIImage.callControlSpeakerEnabled }
    public static var chatLinkCreation: UIImage { UIImage.chatLinkCreation }
    public static var sharedFilesEmptyState: UIImage { UIImage.sharedFilesEmptyState }
    public static var contactInviteSent: UIImage { UIImage.contactInviteSent }
    public static var cookie: UIImage { UIImage.cookie }
    public static var verifyPendingOutshareEmail: UIImage { UIImage.verifyPendingOutshareEmail }
    public static var changeLaunchTab: UIImage { UIImage.changeLaunchTab }
    public static var storageAlmostFull: UIImage { UIImage.storageAlmostFull }
    public static var warningStorageFull: UIImage { UIImage.warningStorageFull  }
    public static var transferLimitedQuota: UIImage { UIImage.transferLimitedQuota }
    public static var transferExceededQuota: UIImage { UIImage.transferExceededQuota }
    public static var _2FASetup: UIImage { UIImage._2FASetup }
    public static var accountUpgradeSecurity: UIImage { UIImage.accountUpgradeSecurity }
    public static var upgradePro: UIImage { UIImage.upgradePro }
    public static var startChat: UIImage { UIImage.startChat }
    public static var uploadFile: UIImage { UIImage.uploadFile }
    public static var phoneCallAll: UIImage { UIImage.phoneCallAll }
    public static var userMicOn: UIImage { UIImage.userMicOn }
    public static var userMutedMeetings: UIImage { UIImage.userMutedMeetings }
    public static var callSlots: UIImage { UIImage.callSlots }
    public static var videoOff: UIImage { UIImage.videoOff }
    public static var sendMessageMeetings: UIImage { UIImage.sendMessageMeetings }
    public static var moderatorMeetings: UIImage { UIImage.moderatorMeetings }
    public static var removeModerator: UIImage { UIImage.removeModerator }
    public static var speakerView: UIImage { UIImage.speakerView }
    public static var muteParticipant: UIImage { UIImage.muteParticipant }
    public static var share: UIImage { UIImage.share }
    public static var callControlSwitchCameraEnabled: UIImage { UIImage.callControlSwitchCameraEnabled }
    public static var callControlSwitchCameraDisabled: UIImage { UIImage.callControlSwitchCameraDisabled }
    public static var shareCallLink: UIImage { UIImage.shareCallLink }
    public static var galleryView: UIImage { UIImage.galleryView }
    public static var micActive: UIImage { UIImage.micActive }
    public static var micMuted: UIImage { UIImage.micMuted }
    public static var jumpToLatest: UIImage { UIImage.jumpToLatest }
    public static var audioCall: UIImage { UIImage.audioCall }
    public static var videoCall: UIImage { UIImage.videoCall }
    public static var megaIconCall: UIImage { UIImage.megaIconCall }
    public static var triangle: UIImage { UIImage.triangle }
    public static var forwardButton: UIImage { UIImage.forwardButton }
    public static var pause: UIImage { UIImage.pause }
    public static var play: UIImage { UIImage.play }
    public static var repeatAudio: UIImage { UIImage.repeatAudio }
    public static var repeatOneAudio: UIImage { UIImage.repeatOneAudio }
    public static var normal: UIImage { UIImage.normal }
    public static var double: UIImage { UIImage.double }
    public static var half: UIImage { UIImage.half }
    public static var oneAndAHalf: UIImage { UIImage.oneAndAHalf }
    public static var lock: UIImage { UIImage.lock }
    public static var callRaiseHand: UIImage { UIImage.callRaiseHand }
    public static var callWithXIncoming: UIImage { UIImage.callWithXIncoming }
    public static var chatroomLoading: UIImage { UIImage.chatroomLoading }
    public static var locationMessage: UIImage { UIImage.locationMessage }
    public static var locationMessageGrey: UIImage { UIImage.locationMessageGrey }
    public static var voiceMessage: UIImage { UIImage.voiceMessage }
    public static var voiceMessageGrey: UIImage { UIImage.voiceMessageGrey }
    public static var activitySendToChat: UIImage { UIImage.activitySendToChat }
    public static var notificationDevicePermission: UIImage { UIImage.notificationDevicePermission }
    public static var glassSearch: UIImage { UIImage.glassSearch }
    public static var videoPlaylistThumbnailFallback: UIImage { UIImage.videoPlaylistThumbnailFallback }
    public static var linksSegmentControler: UIImage { UIImage.linksSegmentControler }
    public static var rectangleVideoStackOutline: UIImage { UIImage.rectangleVideoStackOutline }
    public static var playlist: UIImage { UIImage.playlist }
    public static var navigationBarAdd: UIImage { UIImage.navigationbarAdd }
    public static var timeline: UIImage { UIImage.timeline }
    public static var clockMediumThin: UIImage { UIImage.clockMediumThin }
    public static var glassPlaylist: UIImage { UIImage.glassPlaylist }
    public static var splashScreenMEGALogo: UIImage { UIImage.splashScreenMEGALogo }
    public static var noteToSelf: UIImage { UIImage.noteToSelf }
    public static var sharedFiles: UIImage { UIImage.sharedFiles }
    public static var unArchiveChat: UIImage { UIImage.unArchiveChat }
    public static var sharedFilesInfo: UIImage { UIImage.sharedFilesInfo }
    public static var manageChatHistory: UIImage { UIImage.manageChatHistory }
    public static var meetingLink: UIImage { UIImage.meetingLink }
    public static var onboardingCarousel1: UIImage { UIImage.onboardingCarousel1 }
    public static var onboardingCarousel2: UIImage { UIImage.onboardingCarousel2 }
    public static var onboardingCarousel3: UIImage { UIImage.onboardingCarousel3 }
    public static var onboardingCarousel4: UIImage { UIImage.onboardingCarousel4 }
    public static var photoCardPlaceholder: UIImage { UIImage.photoCardPlaceholder }
    public static var enableCameraUploadsBannerIcon: UIImage { UIImage.enableCameraUploadsBannerIcon }
    public static var cuBannerChevronRevamp: UIImage { UIImage.cuBannerChevronRevamp }
    public static var addContactMeetings: UIImage { UIImage.addContactMeetings }
    public static var filetypeFolder: UIImage { UIImage.filetypeFolder }
    public static var filetype3D: UIImage { UIImage.filetype3D }
    public static var filetypeRaw: UIImage { UIImage.filetypeRaw }
    public static var filetypeVideo: UIImage { UIImage.filetypeVideo }
    public static var filetypeAudio: UIImage { UIImage.filetypeAudio }
    public static var filetypeCompressed: UIImage { UIImage.filetypeCompressed }
    public static var filetypePhotoshop: UIImage { UIImage.filetypePhotoshop }
    public static var filetypeWebLang: UIImage { UIImage.filetypeWebLang }
    public static var filetypeAfterEffects: UIImage { UIImage.filetypeAfterEffects }
    public static var filetypeIllustrator: UIImage { UIImage.filetypeIllustrator }
    public static var filetypeText: UIImage { UIImage.filetypeText }
    public static var filetypeExecutable: UIImage { UIImage.filetypeExecutable }
    public static var filetypeVector: UIImage { UIImage.filetypeVector }
    public static var filetypeImages: UIImage { UIImage.filetypeImages }
    public static var filetypeWebData: UIImage { UIImage.filetypeWebData }
    public static var filetypeWord: UIImage { UIImage.filetypeWord }
    public static var filetypeCAD: UIImage { UIImage.filetypeCAD }
    public static var filetypeDmg: UIImage { UIImage.filetypeDmg }
    public static var filetypeFont: UIImage { UIImage.filetypeFont }
    public static var filetypeSpreadsheet: UIImage { UIImage.filetypeSpreadsheet }
    public static var filetypeIndesign: UIImage { UIImage.filetypeIndesign }
    public static var filetypePowerpoint: UIImage { UIImage.filetypePowerpoint }
    public static var filetypeKeynote: UIImage { UIImage.filetypeKeynote }
    public static var filetypeNumbers: UIImage { UIImage.filetypeNumbers }
    public static var filetypeGeneric: UIImage { UIImage.filetypeGeneric }
    public static var filetypeOpenoffice: UIImage { UIImage.filetypeOpenoffice }
    public static var filetypeExcel: UIImage { UIImage.filetypeExcel }
    public static var filetypePages: UIImage { UIImage.filetypePages }
    public static var filetypePdf: UIImage { UIImage.filetypePdf }
    public static var filetypePremiere: UIImage { UIImage.filetypePremiere }
    public static var filetypeSketch: UIImage { UIImage.filetypeSketch }
    public static var filetypeTorrent: UIImage { UIImage.filetypeTorrent }
    public static var filetypeUrl: UIImage { UIImage.filetypeUrl }
    public static var filetypeExperiencedesign: UIImage { UIImage.filetypeExperiencedesign }
    public static var filetypeFolderCamera: UIImage { UIImage.filetypeFolderCamera }
    public static var achievementsFreeTrialVPN: UIImage { UIImage.achievementsFreeTrialVPN }
    public static var achievementsFreeTrialPass: UIImage { UIImage.achievementsFreeTrialPass }
    public static var tabBarHome: UIImage { UIImage.tabBarHome }
    public static var tabBarDrive: UIImage { UIImage.tabBarDrive }
    public static var tabBarPhotos: UIImage { UIImage.tabBarPhotos }
    public static var tabBarChat: UIImage { UIImage.tabBarChat }
    public static var tabBarMenu: UIImage { UIImage.tabBarMenu }
}
