require_relative "./../ruby/errors_markdown_generator"

module Fastlane
  module Actions
    class GenerateErrorsMarkdownFromJsonAction < Action
      def self.run(params)
        errors_markdown_generator = ErrorsMarkdownGenerator.new()
        return errors_markdown_generator.generate_markdown(params[:json_path], params[:output_file_path], params[:repo_url])
      end

      def self.description
        'Generates warning markdown from json. The output of the fastlane scan is fed to this action.'
      end

      def self.available_options
        [
          FastlaneCore::ConfigItem.new(key: :json_path,
                                       description: "path for the json file generated by scan",
                                       verify_block: proc do |value|
                                          UI.user_error!("No json path given, pass using `json_path: 'path'`") unless (value and not value.empty?)
                                       end),
          FastlaneCore::ConfigItem.new(key: :output_file_path,
                                       description: "file path including the file name where the markdown text needs to be created",
                                       verify_block: proc do |value|
                                          UI.user_error!("No output file path given, pass using `output_file_path: 'path'`") unless (value and not value.empty?)
                                       end),
          FastlaneCore::ConfigItem.new(key: :repo_url,
                                       description: "Repo URL that would be used in the markdown",
                                       verify_block: proc do |value|
                                          UI.user_error!("No repo url given, pass using `repo_url: 'url'`") unless (value and not value.empty?)
                                       end)
        ]
      end

      def self.output
        []
      end

      def self.return_value
        "Boolean: true if the markdown file was generated, false otherwise"
      end

      def self.authors
        ['MEGA']
      end

      def self.is_supported?(platform)
        platform == :ios
      end
    end
  end
end