import ArgumentParser
import Foundation
 
@main
struct CodeCoverageParser: ParsableCommand {
    static let configuration = CommandConfiguration(
        abstract: "Parses a code coverage json file generated by xcov, formats it in the mardown format and writes to a file at a specified path",
        version: "0.0.1"
    )
    
    @Option(help: "input file path of the json to be parsed")
    var input: String
    
    @Option(help: "output file path for the markdown")
    var output: String
    
    mutating func run() throws {
        let jsonFileURL = URL(fileURLWithPath: input)
        let jsonData = try Data(contentsOf: jsonFileURL)
        guard let coverageDetails = try JSONSerialization.jsonObject(with: jsonData, options: []) as? [String: Double] else {
            throw "Unable to read the coverage data from file"
        }
        
        let targetCoverages = coverageDetails.map { key, value in CodeCoverage(name: key, coverage: value) }
        var outputString = """
        
        ## Unit test coverage result
        Target | Percentage
        --- | --- \n
        """
        for targetCoverage in targetCoverages {
            if let coveragePercent = (targetCoverage.coverage).percent {
                let targetCoverageString = targetCoverage.name + " | " + "\(coveragePercent) \n"
                outputString.append(targetCoverageString)
            }
        }
        
        let outputURL = URL(fileURLWithPath: output)
        try outputString.write(to: outputURL, atomically: true, encoding: .utf8)
    }
}




