# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

app_identifier("mega.ios")
force(true)
precheck_default_rule_level(:skip)
precheck_include_in_app_purchases(false)