public enum UserAttributeEntity: Sendable {
    case avatar
    case firstName
    case lastName
    case authRing
    case lastInteraction
    case eD25519PublicKey
    case cU25519PublicKey
    case keyring
    case sigRsaPublicKey
    case sigCU255PublicKey
    case language
    case pwdReminder
    case disableVersions
    case contactLinkVerification
    case richPreviews
    case rubbishTime
    case lastPSA
    case storageState
    case geolocation
    case cameraUploadsFolder
    case myChatFilesFolder
    case pushSettings
    case alias
    case deviceNames
    case backupsFolder
    case cookieSettings
    case jsonSyncConfigData
    case drivesName
    case noCallKit
    case appsPreferences
    case contentConsumptionPreferences
    case lastReadNotification
}
